version: 1

services:
  - name: dash-sqlite-app
    type: web
    runtime: python
    region: singapore
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app.server --bind 0.0.0.0:$PORT
    envVars:
      DASH_ENV: production
